using Injectlynx.Cli;
using Injectlynx.Plugins;
using Microsoft.Extensions.DependencyInjection;

namespace Injectlynx.Cli.Tests;

public sealed class InjectlynxCliTests
{
    [Fact]
    public void Help_PrintsCommands()
    {
        var output = new StringWriter();

        var exitCode = InjectlynxCli.Run(["--help"], output, Directory.GetCurrentDirectory());

        Assert.Equal(0, exitCode);
        Assert.Contains("injectlynx inspect", output.ToString());
        Assert.Contains("injectlynx validate", output.ToString());
    }

    [Fact]
    public void Conventions_PrintsConventionDslMatches()
    {
        using var workspace = new TemporaryWorkspace();
        workspace.Write("ApplicationServiceConventions.cs", """
        using Injectlynx;

        public static class ApplicationServiceConventions
        {
            public static void Configure(IServiceConventionBuilder services)
            {
                services
                    .FromNamespace("Sample.Services")
                    .WhereNameEndsWith("Service")
                    .AsMatchingInterface()
                    .WithScopedLifetime();
            }
        }
        """);
        var output = new StringWriter();

        var exitCode = InjectlynxCli.Run(["conventions", workspace.Root], output, workspace.Root);

        Assert.Equal(0, exitCode);
        Assert.Contains("FromNamespace", output.ToString());
        Assert.Contains("WithScopedLifetime", output.ToString());
    }

    [Fact]
    public void Inspect_PrintsGeneratedReportText()
    {
        using var workspace = new TemporaryWorkspace();
        WriteReport(workspace);
        var output = new StringWriter();

        var exitCode = InjectlynxCli.Run(["inspect", workspace.Root], output, workspace.Root);

        Assert.Equal(0, exitCode);
        Assert.Contains("Injectlynx registration report for module Application", output.ToString());
        Assert.Contains("IOrderService -> OrderService", output.ToString());
    }

    [Fact]
    public void Graph_WritesMermaidOutputFile()
    {
        using var workspace = new TemporaryWorkspace();
        WriteReport(workspace);
        var outputPath = Path.Combine(workspace.Root, "graph.mmd");
        var output = new StringWriter();

        var exitCode = InjectlynxCli.Run(["graph", workspace.Root, "--output", outputPath], output, workspace.Root);

        Assert.Equal(0, exitCode);
        Assert.True(File.Exists(outputPath));
        Assert.Contains("flowchart LR", File.ReadAllText(outputPath));
    }

    [Fact]
    public void Diagnostics_WritesMarkdownExport()
    {
        using var workspace = new TemporaryWorkspace();
        WriteReport(workspace);
        var outputPath = Path.Combine(workspace.Root, "diagnostics.md");
        var output = new StringWriter();

        var exitCode = InjectlynxCli.Run(["diagnostics", workspace.Root, "--output", outputPath], output, workspace.Root);

        Assert.Equal(0, exitCode);
        var text = File.ReadAllText(outputPath);
        Assert.Contains("# Injectlynx Dependency Graph Diagnostics", text);
        Assert.Contains("```mermaid", text);
    }

    [Fact]
    public void PluginsList_PrintsDiscoveredPlugin()
    {
        using var workspace = new TemporaryWorkspace();
        var assemblyName = Path.GetFileName(typeof(CliSamplePlugin).Assembly.Location);
        var assemblyPath = Path.Combine(workspace.Root, assemblyName);
        File.Copy(typeof(CliSamplePlugin).Assembly.Location, assemblyPath, overwrite: true);
        var output = new StringWriter();

        var exitCode = InjectlynxCli.Run(["plugins", "list", "--assembly", assemblyPath], output, workspace.Root);

        Assert.Equal(0, exitCode);
        Assert.Contains("CliSamplePlugin", output.ToString());
    }

    private static void WriteReport(TemporaryWorkspace workspace)
    {
        workspace.Write(Path.Combine("obj", "Debug", "net10.0", "Injectlynx.Application.Report.g.cs"), """
        // <auto-generated />
        #nullable enable

        namespace Microsoft.Extensions.DependencyInjection;

        internal static class InjectlynxApplicationRegistrationReport
        {
            public const string Text = @"Injectlynx registration report for module Application
        Generated method: Microsoft.Extensions.DependencyInjection.AddInjectlynxServices
        Registration count: 1

        - Scoped: IOrderService -> OrderService
          reason: Convention matched.
          detail: Class name ends with Service.
        ";

            public const string Mermaid = @"flowchart LR
          module[""Application module""]
          contract_IOrderService[""IOrderService""]
          implementation_OrderService[""OrderService""]
          module -->|Scoped| contract_IOrderService
          contract_IOrderService --> implementation_OrderService
        ";
        }
        """);
    }

    public sealed class CliSamplePlugin : IInjectlynxPlugin
    {
        public string Name => "CliSamplePlugin";

        public string Description => "Plugin used by CLI tests.";

        public int Order => 0;

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<CliSamplePlugin>();
        }
    }

    private sealed class TemporaryWorkspace : IDisposable
    {
        public string Root { get; } = Path.Combine(Path.GetTempPath(), "InjectlynxCliTests_" + Guid.NewGuid().ToString("N"));

        public TemporaryWorkspace()
        {
            Directory.CreateDirectory(Root);
        }

        public void Write(string relativePath, string contents)
        {
            var path = Path.Combine(Root, relativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, contents);
        }

        public void Dispose()
        {
            if (Directory.Exists(Root))
            {
                Directory.Delete(Root, recursive: true);
            }
        }
    }
}
