using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Injectlynx.Core.Models;

namespace Injectlynx.Generator;

internal static class RegistrationReportSourceWriter
{
    public static string Write(ModuleModel module, ImmutableArray<GeneratedRegistration> registrations)
    {
        var typeName = "Injectlynx" + Sanitize(module.Identity.Name) + "RegistrationReport";
        var report = WriteTextReport(module, registrations);
        var mermaid = WriteMermaidGraph(module, registrations);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(module.GeneratedNamespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("internal static class ").Append(typeName).AppendLine();
        builder.AppendLine("{");
        builder.Append("    public const string Text = ").Append(ToVerbatimStringLiteral(report)).AppendLine(";");
        builder.AppendLine();
        builder.Append("    public const string Mermaid = ").Append(ToVerbatimStringLiteral(mermaid)).AppendLine(";");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string WriteTextReport(ModuleModel module, ImmutableArray<GeneratedRegistration> registrations)
    {
        var builder = new StringBuilder();
        builder.Append("Injectlynx registration report for module ").AppendLine(module.Identity.Name);
        builder.Append("Generated method: ").Append(module.GeneratedNamespace).Append('.').AppendLine(module.GeneratedMethod);
        builder.Append("Registration count: ").AppendLine(registrations.Length.ToString(System.Globalization.CultureInfo.InvariantCulture));
        builder.AppendLine();

        foreach (var registration in registrations.OrderBy(static item => item.Contract, System.StringComparer.Ordinal)
                     .ThenBy(static item => item.Implementation, System.StringComparer.Ordinal)
                     .ThenBy(static item => item.Key, System.StringComparer.Ordinal))
        {
            builder.Append("- ")
                .Append(registration.Lifetime)
                .Append(": ")
                .Append(registration.Contract)
                .Append(" -> ")
                .Append(registration.Implementation);

            if (registration.Key is not null)
            {
                builder.Append(" key=").Append(registration.Key);
            }

            if (registration.Decorators.Length > 0)
            {
                builder.Append(" decorators=").Append(string.Join(" -> ", registration.Decorators));
            }

            if (registration.MemberInjection is not null)
            {
                builder.Append(" member-injection=true");
            }

            builder.AppendLine();
            builder.Append("  reason: ").AppendLine(registration.Reason.Summary);
            foreach (var detail in registration.Reason.Details.Items)
            {
                builder.Append("  detail: ").AppendLine(detail);
            }
        }

        return builder.ToString();
    }

    private static string WriteMermaidGraph(ModuleModel module, ImmutableArray<GeneratedRegistration> registrations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("flowchart LR");
        builder.Append("  module[\"").Append(EscapeMermaid(module.Identity.Name)).AppendLine(" module\"]");

        foreach (var registration in registrations.OrderBy(static item => item.Contract, System.StringComparer.Ordinal)
                     .ThenBy(static item => item.Implementation, System.StringComparer.Ordinal)
                     .ThenBy(static item => item.Key, System.StringComparer.Ordinal))
        {
            var contractId = NodeId("contract_" + registration.Contract);
            var implementationId = NodeId("implementation_" + registration.Implementation);
            builder.Append("  ")
                .Append(contractId)
                .Append("[\"")
                .Append(EscapeMermaid(ShortName(registration.Contract)))
                .AppendLine("\"]");
            builder.Append("  ")
                .Append(implementationId)
                .Append("[\"")
                .Append(EscapeMermaid(ShortName(registration.Implementation)))
                .AppendLine("\"]");
            builder.Append("  module -->|")
                .Append(registration.Lifetime)
                .Append("| ")
                .Append(contractId)
                .AppendLine();
            builder.Append("  ")
                .Append(contractId)
                .Append(" --> ")
                .Append(implementationId)
                .AppendLine();

            foreach (var decorator in registration.Decorators)
            {
                var decoratorId = NodeId("decorator_" + decorator);
                builder.Append("  ")
                    .Append(decoratorId)
                    .Append("[\"")
                    .Append(EscapeMermaid(ShortName(decorator)))
                    .AppendLine("\"]");
                builder.Append("  ")
                    .Append(implementationId)
                    .Append(" --> ")
                    .Append(decoratorId)
                    .AppendLine();
            }
        }

        return builder.ToString();
    }

    private static string ToVerbatimStringLiteral(string value) =>
        "@\"" + value.Replace("\"", "\"\"") + "\"";

    private static string ShortName(string fullyQualifiedName)
    {
        var name = fullyQualifiedName.Replace("global::", string.Empty);
        var genericIndex = name.IndexOf('<');
        var prefix = genericIndex >= 0 ? name.Substring(0, genericIndex) : name;
        var dotIndex = prefix.LastIndexOf('.');
        return dotIndex >= 0 ? prefix.Substring(dotIndex + 1) + (genericIndex >= 0 ? name.Substring(genericIndex) : string.Empty) : name;
    }

    private static string NodeId(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.ToString();
    }

    private static string Sanitize(string value) =>
        new(value.Select(static character => char.IsLetterOrDigit(character) ? character : '_').ToArray());

    private static string EscapeMermaid(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
