using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Injectlynx.Core.Models;

namespace Injectlynx.Generator;

internal static class RegistrationSourceWriter
{
    public static string Write(ModuleModel module, ImmutableArray<GeneratedRegistration> registrations)
    {
        var typeName = "Injectlynx" + module.Identity.Name + "ServiceCollectionExtensions";
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(module.GeneratedNamespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("public static class ").Append(typeName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.Append("    /// Adds Injectlynx-generated registrations for the ").Append(module.Identity.Name).AppendLine(" module.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection " + module.GeneratedMethod + "(");
        builder.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        builder.AppendLine("    {");

        foreach (var registration in registrations)
        {
            WriteReason(builder, registration);
            builder.AppendLine("        " + WriteRegistration(registration));
        }

        builder.AppendLine();
        builder.AppendLine("        return services;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string WriteRegistration(GeneratedRegistration registration)
    {
        var methodName = registration.Lifetime switch
        {
            ServiceLifetimeModel.Singleton => "AddSingleton",
            ServiceLifetimeModel.Scoped => "AddScoped",
            _ => "AddTransient"
        };

        if (IsOpenGeneric(registration.Contract) || IsOpenGeneric(registration.Implementation))
        {
            if (registration.Key is not null)
            {
                return "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions." +
                    methodName.Replace("Add", "AddKeyed") +
                    "(services, typeof(" +
                    registration.Contract +
                    "), typeof(" +
                    registration.Implementation +
                    "), " +
                    ToStringLiteral(registration.Key) +
                    ");";
            }

            return "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions." +
                methodName +
                "(services, typeof(" +
                registration.Contract +
                "), typeof(" +
                registration.Implementation +
                "));";
        }

        if (registration.Key is not null)
        {
            return "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions." +
                methodName.Replace("Add", "AddKeyed") +
                "<" +
                registration.Contract +
                ", " +
                registration.Implementation +
                ">(services, " +
                ToStringLiteral(registration.Key) +
                ");";
        }

        if (registration.Decorators.Length > 0 || registration.MemberInjection is not null)
        {
            return "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions." +
                methodName +
                "<" +
                registration.Contract +
                ">(services, static serviceProvider =>\n" +
                "        {\n" +
                WriteFactoryBody(registration) +
                "        });";
        }

        return "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions." +
            methodName +
            "<" +
            registration.Contract +
            ", " +
            registration.Implementation +
            ">(services);";
    }

    private static bool IsOpenGeneric(string typeName) =>
        typeName.Contains("<>") ||
        typeName.Contains("<,>") ||
        typeName.Contains("<,,>") ||
        typeName.Contains("<,,,>");

    private static string WriteDecoratorFactoryExpression(GeneratedRegistration registration)
    {
        var expression = "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<" +
            registration.Implementation +
            ">(serviceProvider)";

        foreach (var decorator in registration.Decorators)
        {
            expression = "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<" +
                decorator +
                ">(serviceProvider, " +
                expression +
                ")";
        }

        return expression;
    }

    private static string WriteFactoryBody(GeneratedRegistration registration)
    {
        var builder = new StringBuilder();
        builder.Append("            var implementation = ")
            .Append("global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<")
            .Append(registration.Implementation)
            .AppendLine(">(serviceProvider);");

        if (registration.MemberInjection is not null)
        {
            foreach (var property in registration.MemberInjection.Properties)
            {
                builder.Append("            implementation.")
                    .Append(property.Name)
                    .Append(" = ")
                    .Append(property.Optional
                        ? "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<"
                        : "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                    .Append(property.Type)
                    .AppendLine(">(serviceProvider);");
            }

            foreach (var method in registration.MemberInjection.Methods)
            {
                builder.Append("            implementation.")
                    .Append(method.Name)
                    .Append('(')
                    .Append(string.Join(", ", method.Arguments.Select(argument => argument.ValueExpression ??
                        "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<" +
                        argument.Type +
                        ">(serviceProvider)")))
                    .AppendLine(");");
            }
        }

        var expression = "implementation";
        foreach (var decorator in registration.Decorators)
        {
            expression = "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<" +
                decorator +
                ">(serviceProvider, " +
                expression +
                ")";
        }

        builder.Append("            return ").Append(expression).AppendLine(";");
        return builder.ToString();
    }

    private static void WriteReason(StringBuilder builder, GeneratedRegistration registration)
    {
        builder.AppendLine("        // Injectlynx registration");
        builder.Append("        // Reason: ").AppendLine(EscapeComment(registration.Reason.Summary));
        foreach (var detail in registration.Reason.Details.Items)
        {
            builder.Append("        // - ").AppendLine(EscapeComment(detail));
        }
    }

    private static string EscapeComment(string value) =>
        value.Replace("\r", string.Empty).Replace("\n", " ");

    private static string ToStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            if (character == '\\' || character == '"')
            {
                builder.Append('\\');
            }

            builder.Append(character);
        }

        builder.Append('"');
        return builder.ToString();
    }
}
